// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALF-4qDJi-WTvSVbWnTHLMDZA5RzL8WCg',
    appId: '1:8950354546:web:44ae00183485421f2c28eb',
    messagingSenderId: '8950354546',
    projectId: 'fir-sample-cda41',
    authDomain: 'fir-sample-cda41.firebaseapp.com',
    databaseURL: 'https://fir-sample-cda41-default-rtdb.firebaseio.com',
    storageBucket: 'fir-sample-cda41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEht3lLCWGI97rr2HVasj8TZMmc2XrvM',
    appId: '1:8950354546:android:423d2ffd07fc94c22c28eb',
    messagingSenderId: '8950354546',
    projectId: 'fir-sample-cda41',
    databaseURL: 'https://fir-sample-cda41-default-rtdb.firebaseio.com',
    storageBucket: 'fir-sample-cda41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJWGO4qSZZYEzGMN92eCDWC738rH5pwU',
    appId: '1:8950354546:ios:6579cddfb3c1967a2c28eb',
    messagingSenderId: '8950354546',
    projectId: 'fir-sample-cda41',
    databaseURL: 'https://fir-sample-cda41-default-rtdb.firebaseio.com',
    storageBucket: 'fir-sample-cda41.appspot.com',
    iosClientId: '8950354546-t7kdsgbc00f9q893nqhdgu03i383tuo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJWGO4qSZZYEzGMN92eCDWC738rH5pwU',
    appId: '1:8950354546:ios:6579cddfb3c1967a2c28eb',
    messagingSenderId: '8950354546',
    projectId: 'fir-sample-cda41',
    databaseURL: 'https://fir-sample-cda41-default-rtdb.firebaseio.com',
    storageBucket: 'fir-sample-cda41.appspot.com',
    iosClientId: '8950354546-t7kdsgbc00f9q893nqhdgu03i383tuo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogins',
  );
}
